/**
 * Lua Executor Generator
 *
 * Generates the content of ivr_executor.lua — the single generic script
 * deployed to FreeSWITCH that handles ALL IVR flows.
 *
 * The script reads the flow graph at call-time from the ENRS backend API,
 * so no per-flow Lua files are needed. Only this one file is deployed.
 *
 * HTTP transport: curl via io.popen (NOT luasocket). Every other Lua script
 * in this codebase (Lua-scripts/*.lua) already uses this pattern — it avoids
 * a hard dependency on lua-socket, which is not installed by default on a
 * fresh Debian FreeSWITCH box and previously caused a fully silent call
 * failure ("module 'socket.http' not found", call just hangs up) with no
 * indication of why. cjson is used when available (usually bundled with
 * mod_lua) with a minimal pure-Lua fallback decoder/encoder so the script
 * still runs without it.
 *
 * Phase 3: per-node-type handler functions and the dispatch table are no
 * longer hardcoded here — they're generated from
 * backend/src/nodeTypes/registry.js, the single source of truth for every
 * node type. Adding a new node type never requires editing this file's
 * loop — see docs/EXTENDING_NODE_TYPES.md.
 */

import { NODE_TYPE_REGISTRY } from '../nodeTypes/registry.js';

function buildNodeHandlers() {
  return NODE_TYPE_REGISTRY.map(n => n.luaHandler.trim()).join('\n\n');
}

function buildDispatchTable() {
  const entries = NODE_TYPE_REGISTRY.map(n => {
    // "goto" has been a reserved word since Lua 5.2 and cannot be used as
    // a bare table-constructor key (`goto = fn` is a syntax error) — it
    // must be written as a string-indexed key. This is the ONE piece of
    // per-type special-casing left in the generator loop itself, because
    // it's a Lua language rule, not a property of any given node type —
    // every other type flows through uniformly.
    const key = n.type === 'goto' ? '["goto"]' : n.type;
    const padding = ' '.repeat(Math.max(1, 15 - key.length));
    return `  ${key}${padding}= exec_${n.type},`;
  });
  return entries.join('\n');
}

export function generateIvrExecutorLua({ apiBase, apiKey, ttsEngine = 'flite|kal' }) {
  // Sanitise inputs — these are embedded verbatim in the Lua file
  const safeApiBase  = String(apiBase  || 'http://127.0.0.1:4100').replace(/"/g, '\\"');
  const safeApiKey   = String(apiKey   || '').replace(/"/g, '\\"');
  const safeTts      = String(ttsEngine || 'flite|kal').replace(/"/g, '\\"');

  return [
    '-- ============================================================',
    '-- ivr_executor.lua  —  ENRS IVR Flow Executor',
    '-- Generated by ENRS IVR Builder. DO NOT EDIT MANUALLY.',
    '-- Regenerate via: IVR Builder → Deploy button.',
    '-- ============================================================',
    '',
    '-- ── Configuration ──────────────────────────────────────────────',
    `local API_BASE     = "${safeApiBase}/api/v1/internal"`,
    `local API_KEY      = "${safeApiKey}"`,
    `local TTS_ENGINE   = "${safeTts}"   -- engine|voice format`,
    'local MAX_STEPS    = 100            -- safety cap for loop detection',
    'local HTTP_TIMEOUT = 8              -- curl timeout in seconds',
    '',
    '-- ── JSON (cjson is usually bundled with mod_lua; fall back if not) ──',
    '',
    'local json_ok, json = pcall(require, "cjson")',
    'if not json_ok then',
    '  freeswitch.consoleLog("WARN", "[ivr_executor] cjson not available, using minimal JSON fallback\\n")',
    '  json = {',
    '    decode = function(s)',
    '      local fn = load("return " .. s:gsub(\'(%b{})%s*:\', function(k) return k .. "=" end):gsub(\'"([^"]+)"\', "\'%1\'"))',
    '      local ok, v = pcall(fn or function() end)',
    '      return ok and v or nil',
    '    end,',
    '    encode = function(t)',
    '      local parts = {}',
    '      for k, v in pairs(t) do',
    '        local val',
    '        if type(v) == "string" then val = \'"\' .. v:gsub(\'"\', \'\\\\"\') .. \'"\'',
    '        elseif type(v) == "number" then val = tostring(v)',
    '        elseif type(v) == "boolean" then val = tostring(v)',
    '        end',
    '        if val then parts[#parts+1] = \'"\' .. k .. \'":\' .. val end',
    '      end',
    '      return "{" .. table.concat(parts, ",") .. "}"',
    '    end,',
    '  }',
    'end',
    '',
    '-- ── HTTP via curl (io.popen) — no luasocket dependency ────────────',
    '',
    'local function url_encode(s)',
    '  return (tostring(s or "")):gsub("[^%w%-%.%_%~]", function(c)',
    '    return string.format("%%%02X", string.byte(c))',
    '  end)',
    'end',
    '',
    'local function http_request(method, url_path, body_obj)',
    '  local url  = API_BASE .. url_path',
    '  local cmd',
    '  if method == "GET" then',
    '    cmd = string.format(',
    '      \'curl -s -m %d -H "X-Internal-Key: %s" "%s" 2>/dev/null\',',
    '      HTTP_TIMEOUT, API_KEY, url)',
    '  else',
    '    local body_str = body_obj and json.encode(body_obj) or "{}"',
    '    local safe_body = body_str:gsub("\'", "\'\\\\\'\'")',
    '    cmd = string.format(',
    '      "curl -s -m %d -X %s -H \'Content-Type: application/json\' -H \'X-Internal-Key: %s\' -d \'%s\' \'%s\' 2>/dev/null",',
    '      HTTP_TIMEOUT, method, API_KEY, safe_body, url)',
    '  end',
    '',
    '  local h    = io.popen(cmd)',
    '  local body = (h and h:read("*a")) or ""',
    '  if h then h:close() end',
    '',
    '  if body == "" then',
    '    freeswitch.consoleLog("WARN",',
    '      "[ivr_executor] " .. method .. " " .. url_path .. " => empty response\\n")',
    '    return nil',
    '  end',
    '  local ok, data = pcall(json.decode, body)',
    '  if not ok or data == nil then',
    '    freeswitch.consoleLog("ERR", "[ivr_executor] JSON parse error for " .. url_path .. ": " .. tostring(data) .. "\\n")',
    '    return nil',
    '  end',
    '  return data',
    'end',
    '',
    'local function get(p)     return http_request("GET",  p, nil)  end',
    'local function post(p, b) return http_request("POST", p, b)    end',
    '',
    '-- ── Variable interpolation ───────────────────────────────────────',
    '',
    'local function interp(s, str)',
    '  if not str then return "" end',
    '  return (str:gsub("${([^}]+)}", function(k)',
    '    return s:getVariable(k) or ""',
    '  end))',
    'end',
    '',
    '-- ── Audio resolution ─────────────────────────────────────────────',
    '',
    '-- Get sounds_dir from running FreeSWITCH at startup',
    'local _api       = freeswitch.API()',
    'local SOUNDS_DIR = _api:execute("global_getvar", "sounds_dir") or "/usr/share/freeswitch/sounds"',
    '',
    'local function resolve_audio(uri)',
    '  if not uri or uri == "" then return nil end',
    '  if uri:sub(1,7) == "/media/" then',
    '    return SOUNDS_DIR .. "/enrs/" .. uri:sub(8)',
    '  end',
    '  return uri',
    'end',
    '',
    '-- ── TTS speak ────────────────────────────────────────────────────',
    '',
    'local function speak(s, text)',
    '  if not text or text == "" then return end',
    '  s:execute("speak", TTS_ENGINE .. "|" .. text)',
    'end',
    '',
    '-- ── Node executors (generated from nodeTypes/registry.js) ─────────',
    '',
    buildNodeHandlers(),
    '',
    '-- ── Executor dispatch table ───────────────────────────────────────',
    '-- NOTE: "goto" is a reserved word since Lua 5.2 and cannot be used as',
    '-- a bare table-constructor key (`goto = fn` is a syntax error) — it',
    '-- must be written as a string-indexed key.',
    '',
    'local EXEC = {',
    buildDispatchTable(),
    '}',
    '',
    '-- ── Main ─────────────────────────────────────────────────────────',
    '',
    'if not session:ready() then return end',
    '',
    'session:answer()',
    'session:setAutoHangup(false)',
    '',
    'local dest = session:getVariable("destination_number") or ""',
    'freeswitch.consoleLog("INFO", "[ivr_executor] Fetching IVR for number=" .. dest .. "\\n")',
    '',
    '-- entry_node_id and nodes are TOP-LEVEL fields on the lookup response,',
    '-- not nested under a "graph" key.',
    'local data = get("/ivr/lookup?number=" .. url_encode(dest))',
    'if not data or not data.entry_node_id then',
    '  freeswitch.consoleLog("ERR",',
    '    "[ivr_executor] No IVR flow found for number=" .. dest .. "\\n")',
    '  session:hangup("NO_ROUTE_DESTINATION")',
    '  return',
    'end',
    '',
    'local nodes  = data.nodes or {}',
    'local cur_id = data.entry_node_id',
    'local steps  = 0',
    '',
    'while cur_id and steps < MAX_STEPS and session:ready() do',
    '  steps = steps + 1',
    '  local node = nodes[cur_id]',
    '  if not node then',
    '    freeswitch.consoleLog("ERR",',
    '      "[ivr_executor] Node not found: " .. tostring(cur_id) .. "\\n")',
    '    break',
    '  end',
    '  local fn = EXEC[node.type]',
    '  if not fn then',
    '    freeswitch.consoleLog("WARN",',
    '      "[ivr_executor] Unknown node type: " .. tostring(node.type) .. "\\n")',
    '    break',
    '  end',
    '  freeswitch.consoleLog("DEBUG",',
    '    "[ivr_executor] step=" .. steps .. " node=" .. cur_id .. " type=" .. node.type .. "\\n")',
    '  local ok, next_id = pcall(fn, session, node)',
    '  if not ok then',
    '    freeswitch.consoleLog("ERR",',
    '      "[ivr_executor] Error in node " .. cur_id .. ": " .. tostring(next_id) .. "\\n")',
    '    break',
    '  end',
    '  cur_id = next_id',
    'end',
    '',
    'if steps >= MAX_STEPS then',
    '  freeswitch.consoleLog("WARN",',
    '    "[ivr_executor] MAX_STEPS (" .. MAX_STEPS .. ") reached for number=" .. dest .. "\\n")',
    'end',
    '',
    'if session:ready() then session:hangup() end',
  ].join('\n');
}
