-- ============================================================
-- ivr_executor.lua  —  ENRS IVR Flow Executor
-- Generated by ENRS IVR Builder. DO NOT EDIT MANUALLY.
-- Regenerate via: IVR Builder → Deploy button.
-- ============================================================

-- ── Configuration ──────────────────────────────────────────────
local API_BASE     = "http://127.0.0.1:4100/api/v1/internal"
local API_KEY      = "c8b1ee12f5a9829ee98a78296e78836aa2e2878da3263f9a38120c2a2cc60dc7"
local TTS_ENGINE   = "flite|kal"   -- engine|voice format
local MAX_STEPS    = 100            -- safety cap for loop detection
local HTTP_TIMEOUT = 8              -- curl timeout in seconds

-- ── JSON (cjson is usually bundled with mod_lua; fall back if not) ──

local json_ok, json = pcall(require, "cjson")
if not json_ok then
  freeswitch.consoleLog("WARN", "[ivr_executor] cjson not available, using minimal JSON fallback\n")
  json = {
    decode = function(s)
      local fn = load("return " .. s:gsub('(%b{})%s*:', function(k) return k .. "=" end):gsub('"([^"]+)"', "'%1'"))
      local ok, v = pcall(fn or function() end)
      return ok and v or nil
    end,
    encode = function(t)
      local parts = {}
      for k, v in pairs(t) do
        local val
        if type(v) == "string" then val = '"' .. v:gsub('"', '\\"') .. '"'
        elseif type(v) == "number" then val = tostring(v)
        elseif type(v) == "boolean" then val = tostring(v)
        end
        if val then parts[#parts+1] = '"' .. k .. '":' .. val end
      end
      return "{" .. table.concat(parts, ",") .. "}"
    end,
  }
end

-- ── HTTP via curl (io.popen) — no luasocket dependency ────────────

local function url_encode(s)
  return (tostring(s or "")):gsub("[^%w%-%.%_%~]", function(c)
    return string.format("%%%02X", string.byte(c))
  end)
end

local function http_request(method, url_path, body_obj)
  local url  = API_BASE .. url_path
  local cmd
  if method == "GET" then
    cmd = string.format(
      'curl -s -m %d -H "X-Internal-Key: %s" "%s" 2>/dev/null',
      HTTP_TIMEOUT, API_KEY, url)
  else
    local body_str = body_obj and json.encode(body_obj) or "{}"
    local safe_body = body_str:gsub("'", "'\\''")
    cmd = string.format(
      "curl -s -m %d -X %s -H 'Content-Type: application/json' -H 'X-Internal-Key: %s' -d '%s' '%s' 2>/dev/null",
      HTTP_TIMEOUT, method, API_KEY, safe_body, url)
  end

  local h    = io.popen(cmd)
  local body = (h and h:read("*a")) or ""
  if h then h:close() end

  if body == "" then
    freeswitch.consoleLog("WARN",
      "[ivr_executor] " .. method .. " " .. url_path .. " => empty response\n")
    return nil
  end
  local ok, data = pcall(json.decode, body)
  if not ok or data == nil then
    freeswitch.consoleLog("ERR", "[ivr_executor] JSON parse error for " .. url_path .. ": " .. tostring(data) .. "\n")
    return nil
  end
  return data
end

local function get(p)     return http_request("GET",  p, nil)  end
local function post(p, b) return http_request("POST", p, b)    end

-- ── Variable interpolation ───────────────────────────────────────

local function interp(s, str)
  if not str then return "" end
  return (str:gsub("${([^}]+)}", function(k)
    return s:getVariable(k) or ""
  end))
end

-- ── Audio resolution ─────────────────────────────────────────────

-- Get sounds_dir from running FreeSWITCH at startup
local _api       = freeswitch.API()
local SOUNDS_DIR = _api:execute("global_getvar", "sounds_dir") or "/usr/share/freeswitch/sounds"

local function resolve_audio(uri)
  if not uri or uri == "" then return nil end
  if uri:sub(1,7) == "/media/" then
    return SOUNDS_DIR .. "/enrs/" .. uri:sub(8)
  end
  return uri
end

-- ── TTS speak ────────────────────────────────────────────────────

local function speak(s, text)
  if not text or text == "" then return end
  s:execute("speak", TTS_ENGINE .. "|" .. text)
end

-- ── Node executors (generated from nodeTypes/registry.js) ─────────

local function exec_play(s, node)
  local f = resolve_audio(node.audio_url)
  if f then s:streamFile(f) end
  return node.next
end

local function exec_say(s, node)
  speak(s, interp(s, node.text))
  return node.next
end

local function exec_gather(s, node)
  local br      = node.branches or {}
  local max_d   = node.max_digits      or 1
  local timeout = (node.timeout_seconds or 10) * 1000
  local terms   = node.terminators     or "#"
  local digits

  local pf = resolve_audio(node.prompt_audio_url)
  if pf then
    digits = s:playAndGetDigits(1, max_d, 3, timeout, terms, pf, "", "[0-9#*]+", "", 0)
  else
    local pt = interp(s, node.prompt_text)
    if pt ~= "" then speak(s, pt) end
    digits = s:getDigits(max_d, terms, timeout)
  end

  s:setVariable(node.variable_name or "gather_result", digits or "")
  return br[digits] or br["_default"] or br["invalid"]
end

local function exec_condition(s, node)
  local op  = node.operator or "=="
  local val = s:getVariable(node.variable or "") or ""
  local exp = interp(s, node.expected_value) or ""
  local ok  = false

  if     op == "==" then
    ok = (val == exp)
  elseif op == "!=" then
    ok = (val ~= exp)
  elseif op == "contains" then
    ok = (val:find(exp, 1, true) ~= nil)
  elseif op == "starts_with" then
    ok = (val:sub(1, #exp) == exp)
  elseif op == "ens_pin_valid" then
    -- PIN check goes through /ens/verify-pin ONLY — it is the single
    -- source of truth for pin_required + correctness (handles "no PIN
    -- configured -> always authorized" internally). /ens/lookup never
    -- reads a pin query param at all; the raw PIN is never echoed back
    -- by lookup, matching the documented contract in CLAUDE.md.
    local dest = exp ~= "" and exp or s:getVariable("destination_number") or ""
    local verify = post("/ens/verify-pin", { trigger_number = dest, pin = val })
    if verify and verify.authorized then
      local lookup = get("/ens/lookup?number=" .. url_encode(dest))
      if lookup and lookup.success and lookup.data then
        s:setVariable("ens_configuration_id", tostring(lookup.data.configuration_id))
        s:setVariable("ens_blast_clid",       lookup.data.blast_clid or "")
      end
      ok = true
    end
  elseif op == "time_of_day" then
    -- expected_value format: "HHMM-HHMM" e.g. "0900-1700"
    local now_hhmm = tonumber(os.date("%H%M")) or 0
    local s_part, e_part = exp:match("^(%d%d%d%d)-(%d%d%d%d)$")
    if s_part and e_part then
      local start_n = tonumber(s_part) or 0
      local end_n   = tonumber(e_part) or 2359
      if start_n <= end_n then
        ok = (now_hhmm >= start_n and now_hhmm < end_n)
      else
        -- overnight range e.g. 2200-0600
        ok = (now_hhmm >= start_n or now_hhmm < end_n)
      end
    end
  elseif op == "day_of_week" then
    -- expected_value: comma-separated day numbers 0=Sun … 6=Sat
    local today = tonumber(os.date("%w")) or -1
    for d in exp:gmatch("%d+") do
      if tonumber(d) == today then ok = true; break end
    end
  elseif op == "ens_callback_valid" then
    -- expected_value carries the reply_clid the caller dialed in on —
    -- matches GET /ens/callbacks/authorize?reply_clid=&caller= exactly.
    local reply_clid = exp ~= "" and exp or ""
    local caller = s:getVariable("caller_id_number") or ""
    local d = get("/ens/callbacks/authorize?reply_clid=" .. url_encode(reply_clid) .. "&caller=" .. url_encode(caller))
    if d and d.authorized then
      s:setVariable("ens_notification_uuid", d.notification_uuid or "")
      s:setVariable("ens_recording_file",    d.recording_file or "")
      s:setVariable("ens_delivery_id",       tostring(d.delivery_id or ""))
      ok = true
    end
  end

  return ok and node.true_node or node.false_node
end

local function exec_goto(s, node)  return node.target_node_id end

local function exec_ens(s, node)
  local cfg_id = node.ens_configuration_id
  if not cfg_id or cfg_id == 0 then
    cfg_id = tonumber(s:getVariable(node.ens_config_var or "ens_configuration_id") or "")
  end
  if not cfg_id then
    freeswitch.consoleLog("ERR", "[ivr_executor] ens node: could not resolve configuration_id — skipping\n")
    return node.next
  end

  local caller_number = s:getVariable("caller_id_number") or ""
  local recording_file
  if node.recording_file_var and node.recording_file_var ~= "" then
    local rf = s:getVariable(node.recording_file_var) or ""
    if rf ~= "" then recording_file = rf end
  end

  local d = post("/ens/notifications", {
    configuration_id = cfg_id,
    triggered_via    = "PHONE",
    caller_number    = caller_number ~= "" and caller_number or nil,
    recording_file   = recording_file,
  })

  if d and d.notification_uuid then
    s:setVariable("ens_notification_uuid", d.notification_uuid)
    freeswitch.consoleLog("INFO", "[ivr_executor] ens node: blast triggered uuid=" .. d.notification_uuid .. "\n")
  else
    freeswitch.consoleLog("ERR", "[ivr_executor] ens node: blast failed — " .. tostring(d and d.error or "no response") .. "\n")
  end

  return node.next
end

local function exec_ers(s, node)
  local cfg_id = node.ers_configuration_id
  if not cfg_id or cfg_id == 0 then
    cfg_id = tonumber(s:getVariable(node.ers_config_var or "ers_configuration_id") or "")
  end
  if not cfg_id then
    freeswitch.consoleLog("ERR", "[ivr_executor] ers node: could not resolve configuration_id — hanging up\n")
    return nil
  end

  -- The API never echoes conference_room back — it is generated here and
  -- reused directly to bridge, matching the constraint the internal API
  -- enforces on the value it is given: ^[a-z0-9_]{1,64}$
  local room = "ers_" .. tostring(cfg_id) .. "_" .. tostring(os.time())

  local d = post("/ers/incidents", {
    configuration_id = cfg_id,
    caller_number    = s:getVariable("caller_id_number") or "",
    conference_room  = room,
    group_type       = node.group_type or "primary",
  })

  if d and d.incident_uuid then
    s:setVariable("ers_incident_uuid", d.incident_uuid)
    s:execute("conference", room .. "@default")
    -- s:execute("conference", ...) blocks until THIS leg leaves the
    -- room. Reuse the already-built /ers/incidents/:uuid/complete
    -- endpoint (handles ers_queues promotion too — do not rebuild that
    -- here) so the incident row stops showing as permanently ACTIVE.
    -- NOTE: this marks "this leg left," not "the room is empty" — a
    -- room with other members still bridged stays live in FreeSWITCH
    -- regardless of this incident row's status; live occupancy must
    -- always be checked via ESL conference member count, never this
    -- status field alone.
    post("/ers/incidents/" .. d.incident_uuid .. "/complete", {
      recording_file = s:getVariable("recorded_file_path") or nil,
    })
  else
    freeswitch.consoleLog("ERR", "[ivr_executor] ers node: incident creation failed — " .. tostring(d and d.error or "no response") .. "\n")
  end
  return nil
end

local function exec_hangup(s, node)
  local f = resolve_audio(node.play_audio_url)
  if f then s:streamFile(f) end
  s:hangup()
  return nil
end

local function exec_record_message(s, node)
  local rec_dir = node.record_dir
  if not rec_dir or rec_dir == "" then
    rec_dir = _api:execute("global_getvar", "recordings_dir") or "/var/lib/freeswitch/recordings"
    rec_dir = rec_dir .. "/ivr"
  end
  local fpath = rec_dir .. "/ivr_" .. s:getVariable("uuid") .. "_" .. os.time() .. ".wav"

  local pf = resolve_audio(node.prompt_audio_url)
  if pf then
    s:streamFile(pf)
  else
    local pt = interp(s, node.prompt_text) or ""
    if pt ~= "" then speak(s, pt) end
  end

  s:execute("playback", "tone_stream://%(500,0,640)")  -- recording beep
  s:recordFile(fpath,
    node.max_seconds       or 60,
    node.silence_threshold or 500,
    node.silence_hits      or 3)
  s:setVariable(node.variable_name or "recorded_file_path", fpath)
  return node.next
end

local function exec_set_variable(s, node)
  s:setVariable(node.variable or "unknown_var", interp(s, node.value) or "")
  return node.next
end

local function exec_transfer(s, node)
  local dest = interp(s, node.destination) or ""
  s:execute("transfer",
    dest .. " " .. (node.dialplan or "XML") .. " " .. (node.context or "default"))
  return nil
end

local function exec_webhook(s, node)
  local url = interp(s, node.url) or ""
  if url == "" then
    freeswitch.consoleLog("ERR", "[ivr_executor] webhook node: empty url — skipping\n")
    return node.next
  end
  -- Fire-and-forget to an arbitrary external URL — deliberately NOT routed
  -- through API_BASE/API_KEY (those are for this app's own internal API
  -- only). Same curl-via-io.popen pattern as every other HTTP call in this
  -- file, just without the internal auth header.
  local body = interp(s, node.body_template) or "{}"
  local safe_body = body:gsub("'", "'\\''")
  local cmd = string.format(
    "curl -s -m %d -X POST -H 'Content-Type: application/json' -d '%s' '%s' 2>/dev/null",
    HTTP_TIMEOUT, safe_body, url)
  local h = io.popen(cmd)
  if h then h:close() end
  return node.next
end

local function exec_ers_ring_all(s, node)
  local cfg_id = node.ers_configuration_id
  if not cfg_id then
    freeswitch.consoleLog("ERR", "[ivr_executor] ers_ring_all: missing ers_configuration_id — hanging up\n")
    speak(s, "This emergency service is not configured. Please call emergency services directly.")
    s:hangup("NORMAL_CLEARING")
    return nil
  end

  local d = post("/ers/ring-all", {
    configuration_id = cfg_id,
    tier             = node.tier or "primary",
    caller_number    = s:getVariable("caller_id_number") or "",
    caller_name      = s:getVariable("caller_id_name") or nil,
  })

  -- d.success == false means the backend rejected the request (e.g. no
  -- responders configured). Never fail silently — log ERR with the reason
  -- and play an audible fallback so the caller is not left in silence.
  if not d or not d.success then
    local reason = (d and d.reason) or "no_response"
    local err_detail = (d and d.error) or "no response from backend"
    freeswitch.consoleLog("ERR",
      "[ivr_executor] ers_ring_all: ring-all failed — reason=" .. reason ..
      " detail=" .. err_detail .. "\n")
    if reason == "no_responders" then
      speak(s, "No emergency responders are currently configured for this service. Please call emergency services directly.")
    else
      speak(s, "The emergency response service is currently unavailable. Please call emergency services directly.")
    end
    s:hangup("NORMAL_CLEARING")
    return nil
  end

  if d.conference_room then
    s:setVariable("ers_incident_uuid", d.incident_uuid or "")
    -- Blocks until THIS leg leaves. The backend ring loop keeps re-ringing
    -- responders in parallel the whole time the caller waits in the room.
    s:execute("conference", d.conference_room .. "@default")
    if d.incident_uuid then
      post("/ers/incidents/" .. d.incident_uuid .. "/complete", {})
    end
  end
  return nil
end

local function exec_ers_overflow_check(s, node)
  local br = node.branches or {}
  local d = get("/ers/tier-status?configuration_id=" .. tostring(node.ers_configuration_id or 0))
  if not d or not d.success then
    freeswitch.consoleLog("ERR", "[ivr_executor] ers_overflow_check: tier-status failed — routing to full branch\n")
    return br["full"]
  end
  if d.primary and not d.primary.occupied then
    return br["primary"]
  elseif d.secondary and not d.secondary.occupied then
    return br["secondary"]
  end
  return br["full"]
end

local function exec_ers_overflow_wait(s, node)
  local enq = post("/ers/overflow/enqueue", {
    configuration_id   = node.ers_configuration_id or 0,
    caller_number      = s:getVariable("caller_id_number") or "",
    caller_name        = s:getVariable("caller_id_name") or nil,
    destination_number = s:getVariable("destination_number") or nil,
  })
  if not enq or not enq.queue_id then
    freeswitch.consoleLog("ERR", "[ivr_executor] ers_overflow_wait: enqueue failed — falling back\n")
    return node.next
  end

  local hold_file = resolve_audio(node.hold_audio_url)
  local hold_text = interp(s, node.hold_prompt_text)
  if hold_file then s:streamFile(hold_file)
  elseif hold_text ~= "" then speak(s, hold_text) end

  local max_wait = node.max_wait_seconds or 300
  local deadline = os.time() + max_wait

  while s:ready() and os.time() < deadline do
    local d = get("/ers/overflow/poll?queue_id=" .. tostring(enq.queue_id))
    if d and d.ready and d.conference_room then
      s:execute("conference", d.conference_room .. "@default")
      if d.incident_uuid then
        post("/ers/incidents/" .. d.incident_uuid .. "/complete", {})
      end
      return nil
    end
    if d and d.cancelled then return node.next end
    -- brief hold-tone loop between polls
    s:execute("playback", "silence_stream://3000")
  end

  return node.next
end

local function exec_ens_blast_record(s, node)
  local dest = s:getVariable("destination_number") or ""

  -- PIN gate — /ens/verify-pin is the single source of truth (handles the
  -- "no PIN configured -> always authorized" case internally).
  local authorized = false
  for attempt = 1, 3 do
    local prompt = interp(s, node.pin_prompt_text)
    if prompt == "" then prompt = "Please enter your authorization PIN followed by pound." end
    speak(s, prompt)
    local pin = s:getDigits(8, "#", 10000)
    local verify = post("/ens/verify-pin", { trigger_number = dest, pin = pin or "" })
    if verify and verify.authorized then
      authorized = true
      break
    end
    speak(s, "Invalid PIN.")
  end
  if not authorized then
    speak(s, "Maximum authorization attempts exceeded. Goodbye.")
    s:hangup("CALL_REJECTED")
    return nil
  end

  -- Resolve configuration_id (node value, else lookup by dialed number)
  local cfg_id = node.ens_configuration_id
  if not cfg_id then
    local lookup = get("/ens/lookup?number=" .. url_encode(dest))
    if lookup and lookup.success and lookup.data then
      cfg_id = lookup.data.configuration_id
    end
  end
  if not cfg_id then
    freeswitch.consoleLog("ERR", "[ivr_executor] ens_blast_record: could not resolve configuration_id\n")
    speak(s, "This notification service is not configured. Goodbye.")
    return nil
  end

  -- Record the initiator's message
  local rec_dir = _api:execute("global_getvar", "recordings_dir") or "/var/lib/freeswitch/recordings"
  local fpath = rec_dir .. "/ens/ens_" .. tostring(cfg_id) .. "_" .. os.time() .. ".wav"
  local rprompt = interp(s, node.record_prompt_text)
  if rprompt == "" then rprompt = "Record your emergency message after the tone. Press pound when finished." end
  speak(s, rprompt)
  s:execute("playback", "tone_stream://%(500,0,640)")
  s:recordFile(fpath, node.max_record_seconds or 120, 500, 3)

  -- Broadcast — reaches every contact's extension AND mobile (see
  -- resolveEnsContacts in ensInternalController.js).
  local d = post("/ens/notifications", {
    configuration_id = cfg_id,
    triggered_via    = "PHONE",
    caller_number    = s:getVariable("caller_id_number") or nil,
    recording_file   = fpath,
  })

  if d and d.notification_uuid then
    s:setVariable("ens_notification_uuid", d.notification_uuid)
    speak(s, "Your emergency notification is now being sent to all contacts.")
  else
    freeswitch.consoleLog("ERR", "[ivr_executor] ens_blast_record: blast failed — " .. tostring(d and d.error or "no response") .. "\n")
    speak(s, "There was a problem starting your notification. Please contact your administrator.")
  end

  return node.next
end

local function exec_ens_playback_gate(s, node)
  local caller = s:getVariable("caller_id_number") or ""
  local d = get("/ers/playback/authorize?configuration_id=" .. tostring(node.ers_configuration_id or 0) ..
                "&caller=" .. url_encode(caller))

  if not d or not d.authorized then
    freeswitch.consoleLog("WARN", "[ivr_executor] ens_playback_gate: rejected caller " .. caller .. " (" .. tostring(d and d.reason or "no response") .. ")\n")
    return node.false_node
  end

  if d.recording_file then
    s:streamFile(d.recording_file)
  else
    local msg = interp(s, node.no_message_text)
    if msg == "" then msg = "There is no active emergency message at this time." end
    speak(s, msg)
  end
  return node.true_node
end

-- ── Executor dispatch table ───────────────────────────────────────
-- NOTE: "goto" is a reserved word since Lua 5.2 and cannot be used as
-- a bare table-constructor key (`goto = fn` is a syntax error) — it
-- must be written as a string-indexed key.

local EXEC = {
  play           = exec_play,
  say            = exec_say,
  gather         = exec_gather,
  condition      = exec_condition,
  ["goto"]       = exec_goto,
  ens            = exec_ens,
  ers            = exec_ers,
  hangup         = exec_hangup,
  record_message = exec_record_message,
  set_variable   = exec_set_variable,
  transfer       = exec_transfer,
  webhook        = exec_webhook,
  ers_ring_all   = exec_ers_ring_all,
  ers_overflow_check = exec_ers_overflow_check,
  ers_overflow_wait = exec_ers_overflow_wait,
  ens_blast_record = exec_ens_blast_record,
  ens_playback_gate = exec_ens_playback_gate,
}

-- ── Main ─────────────────────────────────────────────────────────

if not session:ready() then return end

session:answer()
session:setAutoHangup(false)

local dest = session:getVariable("destination_number") or ""
freeswitch.consoleLog("INFO", "[ivr_executor] Fetching IVR for number=" .. dest .. "\n")

-- entry_node_id and nodes are TOP-LEVEL fields on the lookup response,
-- not nested under a "graph" key.
local data = get("/ivr/lookup?number=" .. url_encode(dest))
if not data or not data.entry_node_id then
  freeswitch.consoleLog("ERR",
    "[ivr_executor] No IVR flow found for number=" .. dest .. "\n")
  session:hangup("NO_ROUTE_DESTINATION")
  return
end

local nodes  = data.nodes or {}
local cur_id = data.entry_node_id
local steps  = 0

while cur_id and steps < MAX_STEPS and session:ready() do
  steps = steps + 1
  local node = nodes[cur_id]
  if not node then
    freeswitch.consoleLog("ERR",
      "[ivr_executor] Node not found: " .. tostring(cur_id) .. "\n")
    break
  end
  local fn = EXEC[node.type]
  if not fn then
    freeswitch.consoleLog("WARN",
      "[ivr_executor] Unknown node type: " .. tostring(node.type) .. "\n")
    break
  end
  freeswitch.consoleLog("DEBUG",
    "[ivr_executor] step=" .. steps .. " node=" .. cur_id .. " type=" .. node.type .. "\n")
  local ok, next_id = pcall(fn, session, node)
  if not ok then
    freeswitch.consoleLog("ERR",
      "[ivr_executor] Error in node " .. cur_id .. ": " .. tostring(next_id) .. "\n")
    break
  end
  cur_id = next_id
end

if steps >= MAX_STEPS then
  freeswitch.consoleLog("WARN",
    "[ivr_executor] MAX_STEPS (" .. MAX_STEPS .. ") reached for number=" .. dest .. "\n")
end

if session:ready() then session:hangup() end